//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wheel01.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WheelFlipDirection {
            get {
                return ((bool)(this["WheelFlipDirection"]));
            }
            set {
                this["WheelFlipDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double WheelRotationRange {
            get {
                return ((double)(this["WheelRotationRange"]));
            }
            set {
                this["WheelRotationRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AccStartHwValue {
            get {
                return ((int)(this["AccStartHwValue"]));
            }
            set {
                this["AccStartHwValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4095")]
        public int AccEndHwValue {
            get {
                return ((int)(this["AccEndHwValue"]));
            }
            set {
                this["AccEndHwValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BrkStartHwValue {
            get {
                return ((int)(this["BrkStartHwValue"]));
            }
            set {
                this["BrkStartHwValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4095")]
        public int BrkEndHwValue {
            get {
                return ((int)(this["BrkEndHwValue"]));
            }
            set {
                this["BrkEndHwValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CltStartHwValue {
            get {
                return ((int)(this["CltStartHwValue"]));
            }
            set {
                this["CltStartHwValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4095")]
        public int CltEndHwValue {
            get {
                return ((int)(this["CltEndHwValue"]));
            }
            set {
                this["CltEndHwValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WheelHwValueOffset {
            get {
                return ((int)(this["WheelHwValueOffset"]));
            }
            set {
                this["WheelHwValueOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WheelHwOverRotationOffset {
            get {
                return ((int)(this["WheelHwOverRotationOffset"]));
            }
            set {
                this["WheelHwOverRotationOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int FFBValueSenderInterval {
            get {
                return ((int)(this["FFBValueSenderInterval"]));
            }
            set {
                this["FFBValueSenderInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FFBMultiplier {
            get {
                return ((int)(this["FFBMultiplier"]));
            }
            set {
                this["FFBMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int FFBLinearity {
            get {
                return ((int)(this["FFBLinearity"]));
            }
            set {
                this["FFBLinearity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FFBFlipVout {
            get {
                return ((bool)(this["FFBFlipVout"]));
            }
            set {
                this["FFBFlipVout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public double FFBMaxVout {
            get {
                return ((double)(this["FFBMaxVout"]));
            }
            set {
                this["FFBMaxVout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int BrkLinearity {
            get {
                return ((int)(this["BrkLinearity"]));
            }
            set {
                this["BrkLinearity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int FFBLinearityMix {
            get {
                return ((int)(this["FFBLinearityMix"]));
            }
            set {
                this["FFBLinearityMix"] = value;
            }
        }
    }
}
